#!mast .yardopts .ruby bin lib spec test [A-Z]*.*
.yardopts
.ruby
lib/wedge/gem.rb
lib/wedge/kernel.rb
lib/wedge/ruby.rb
lib/wedge/version.rb
lib/wedge.rb
spec/fixture/abbrev.rb
spec/helper.rb
spec/ruby_wedge_spec.rb
HISTORY.rdoc
BSD-2.txt
README.rdoc
COPYING.rdoc
INFRACTIONS.rdoc
