#!mast .yardopts .ruby bin lib spec test [A-Z]*.*
.yardopts
.ruby
lib/wedge/gem.rb
lib/wedge/kernel.rb
lib/wedge/ruby.rb
lib/wedge/version.rb
lib/wedge.rb
test/fixture/abbrev.rb
test/wedge.rb
HISTORY.rdoc
BSD-2.txt
README.rdoc
COPYING.rdoc
INFRACTIONS.rdoc
